### ISSUE TITLE
'year select' formatting broken when using 'bootstrap-datetimepicker'

### ISSUE THREAD

**Issue by matthewhegarty** [vedmack/yadcf#669]
When using 'bootstrap-datetimepicker', the formatting is broken if you select the 'year' or 'decade' view:

![Screenshot 2022-11-29 at 13 25 19](https://user-images.githubusercontent.com/6249838/204541859-e6580ea2-9c90-4d17-94f1-6c234ae18139.png)

[JS Fiddle](https://jsfiddle.net/matthewhegarty/eu1adchj/10/)

To reproduce, click on 'From' input box, then the 'year' in the datepicker widget.  The same issue occurs if you select the decade view as well.

I believe the issue comes from the css [here](https://github.com/vedmack/yadcf/blob/241bfc39ec7600ade8693913f700d3e8bb83b048/src/jquery.dataTables.yadcf.css#L47).  Removing `white-space: nowrap;` seems to resolve the issue. 

I fixed this issue as follows:

```css
.yadcf-filter-wrapper .datepicker-months, .yadcf-filter-wrapper .datepicker-years, .yadcf-filter-wrapper .datepicker-decades {
	white-space: normal;
}
```
